name: Build and Deploy Jekyll site

on:
  push:
    branches: [ main ]   # 如果默认分支是 master 就改 master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'     # ← 关键：固定到 3.1
          bundler-cache: false

      - name: Make Gemfile.lock Linux-compatible
        run: |
          if [ -f Gemfile.lock ]; then
            bundle lock --add-platform x86_64-linux
            bundle lock --add-platform ruby
          fi

      - name: Install dependencies
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace --verbose -d _site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
